# NumPy
- NumPy is a Python library used for working with arrays. NumPy is short for "Numerical Python".  
- It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.


In [1]:
import numpy as np
import sys

#List
s = range(1000)
print("Size of each element if list in bytes: ", sys.getsizeof(s))
print("Size of whole list in bytes: ",sys.getsizeof(s)*len(s))

# Numpy Array
D = np.arange(1000)
print("Size of each element of numpy array in bytes: ",D.itemsize)
print("Size of whole numpy array in bytes: ", D.itemsize * D.size)

Size of each element if list in bytes:  48
Size of whole list in bytes:  48000
Size of each element of numpy array in bytes:  4
Size of whole numpy array in bytes:  4000


In [4]:
arr = np.array(41)
print(arr)
print(arr.ndim)
print(type(arr))

print("______________________")
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)
print(type(arr1))

print("______________________")
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.ndim)
print(type(arr2))

41
0
<class 'numpy.ndarray'>
______________________
[1 2 3 4 5]
1
<class 'numpy.ndarray'>
______________________
[[1 2 3 4 5]]
2
<class 'numpy.ndarray'>


In [19]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3[1][2])

arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr4[1][1][1])

[[1 2 3 4]
 [5 6 7 8]]
7
11


In [16]:
arr5  = np.array([1,2,3,4,5])
print(arr5)
print(arr5[3])
# print(arr5[5])
print(arr5[3]+arr5[4])

[1 2 3 4 5]
4
9


In [18]:
arr6 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr6[0,1,2])
print(arr6[1,1,1])
print(arr6[0,0,1])
print(arr6[1,0,2])
print(arr6[1,1,2])


6
11
2
9
12


In [20]:
arr7 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr7[1,3])
print(arr7[1,-3])
print(arr7[1,0:3])

8
6
[5 6 7]


In [24]:
arr8 = np.array([1,2,3,4,5])
print(arr8[1:3])
print(arr8[1:])
print(arr8[0:4:2])
print(arr8[0:5:2])
print(arr8[-3:-1])
print(arr8[::-1])


[2 3]
[2 3 4 5]
[1 3]
[1 3 5]
[3 4]
[5 4 3 2 1]


In [41]:
arr9 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr9[0:2,2])
print(arr9[0:3,2])
print(arr9[0:4,2])
print("________________")
print(arr9[0:2,1])
print(arr9[0:2,3])
# Will give error
# print(arr9[0:2,4])


[3 7]
[3 7]
[3 7]
________________
[2 6]
[4 8]


In [50]:
arr10 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr10[0:2,0:2,0:2])
print("_________________")
print(arr10[0:2,0:2,2])
print("_________________")
print(arr1[1:2])
print("_________________")
print(arr10[0:2,1,0:2])
print("_________________")
print(arr10[0:2,1:2,0:2])
print("_________________")
print(arr10[0:2,1,2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
_________________
[[ 3  6]
 [ 9 12]]
_________________
[2]
_________________
[[ 4  5]
 [10 11]]
_________________
[[[ 4  5]]

 [[10 11]]]
_________________
[ 6 12]


In [52]:
arr11 = np.array([1,2,3,4,5])
arr12 = np.array([[1,2,3,4],[5,6,7,8]])
arr13 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr11.ndim)
print(arr11.shape)
print("_________________")
print(arr12.ndim)
print(arr12.shape)
print("_________________")
print(arr13.ndim)
print(arr13.shape)


1
(5,)
_________________
2
(2, 4)
_________________
3
(2, 2, 3)


In [53]:
arr14 = np.array([[[[[1,2,3,4,5]]]]])
print(arr14.ndim)
print(arr14.shape)



5
(1, 1, 1, 1, 5)


In [65]:
arr15 = np.array([1,2,3,4,5,6])
print(arr15)
newarr15 = arr15.reshape(2,3)
print("_________________")
print(newarr15)

arr16 = np.array([1,2,3,4,5,6])
newarr16 = arr16.reshape(3,2)
print("_________________")
print(newarr16)

arr17 = np.array([1,2,3,4,5,6])
# cannot reshape array of size 6 into shape (4,5,6)
# newarr17 = arr17.reshape(4,5,6)
print("_________________")
# print(newarr17)

arr18 = np.array([1,2,3,4,5,6])
newarr18 = arr18.reshape(1,2,3)
print("_________________")
print(newarr18)

[1 2 3 4 5 6]
_________________
[[1 2 3]
 [4 5 6]]
_________________
[[1 2]
 [3 4]
 [5 6]]
_________________
_________________
[[[1 2 3]
  [4 5 6]]]


In [70]:
arr19 = np.array([1,2,3,4,5,6])
newarr19 = arr19.reshape(1,2,3).base
print("_________________")
print(newarr18)

arr20 = np.array([1,2,3,4,5,6])
newarr20 = arr20.reshape(2,-1)
print("_________________")
print(newarr20)

arr21 = np.array([1,2,3,4,5,6])
newarr21 = arr21.reshape(3,-1)
print("_________________")
print(newarr21)




_________________
[[[1 2 3]
  [4 5 6]]]
_________________
[[1 2 3]
 [4 5 6]]
_________________
[[1 2]
 [3 4]
 [5 6]]


# Iteration


In [76]:
arr22 = np.array([1,2,3,4,5])

for i in arr22:
    print(i)

print("_________________")
arr23 = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr23:
    for j in i:
        print(j)

print("_________________")
arr24 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


for i in arr24:
    for j in i:
        for k in j:
            print(k)
            
print("_________________")
for x in np.nditer([1,2,3,4,5]):
    print(x)
    
print("________________")


arr25 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(arr25[0:1,::2]):
    print(x)

print("________________")
for x in np.nditer(arr25[:,::2]):
    print(x)

    

1
2
3
4
5
_________________
1
2
3
4
5
6
7
8
_________________
1
2
3
4
5
6
7
8
9
10
11
12
_________________
(array(1), array(2), array(3), array(4), array(5))
________________
1
3
5
________________
1
3
5
6
8
10


In [83]:
arr26 = np.array([1,2,3])
arr27 = np.array([4,5,6])
arr28 = np.array([7,8,9])

arrr = np.concatenate((arr26,arr27,arr28))
print(arrr)
print("_________________")

arrr = np.concatenate((arr26,arr27,arr28),axis= 0)
print(arrr)
print("_________________")

arrr = np.concatenate((arr26,arr27,arr28))
print(arrr)
print("_________________")

[1 2 3 4 5 6 7 8 9]
_________________
[1 2 3 4 5 6 7 8 9]
_________________
[1 2 3 4 5 6 7 8 9]
_________________


In [88]:
arr29 = ([[1,2],[3,4]])
arr30 = ([[5,6],[7,8]])

arrr1 = np.concatenate((arr29,arr30),axis = 0)
print(arrr1)

print(arrr1.shape)
print("_________________")

arrr1 = np.concatenate((arr29,arr30),axis = 1)
print(arrr1)

print(arrr1.shape)
print("_________________")



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
_________________
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)
_________________


# Split


In [96]:
arr31 = np.array([1,2,3,4])
newarr31 = np.array_split(arr31,1)
print(newarr31)

print("_________________")
newarr31 = np.array_split(arr31,2)
print(newarr31)

print("_________________")
newarr31 = np.array_split(arr31,3)
print(newarr31)

print("_________________")
newarr31 = np.array_split(arr31,4)
print(newarr31)


[array([1, 2, 3, 4])]
_________________
[array([1, 2]), array([3, 4])]
_________________
[array([1, 2]), array([3]), array([4])]
_________________
[array([1]), array([2]), array([3]), array([4])]


In [109]:
arr32 = ([[1,2],[3,4],[5,6],[7,8]])
newarr32 = np.array_split(arr32,1)
print(newarr32)

print("_________________")
newarr32 = np.array_split(arr32,2)
print(newarr32)

print("_________________")
newarr32 = np.array_split(arr32,3)
print(newarr32)

print("_________________")
newarr32 = np.array_split(arr32,4)
print(newarr32)

print("_________________")
newarr32 = np.array_split(arr32,6)
print(newarr32)

[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])]
_________________
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
_________________
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]
_________________
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]
_________________
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]


In [106]:
arr32 = ([[1,2],[3,4],[5,6],[7,8]])
print("_________________ 1 1")
newarr32 = np.array_split(arr32,1,axis = 1)
print(newarr32)

print("_________________ 2 1")
newarr32 = np.array_split(arr32,2,axis = 1)
print(newarr32)

print("_________________ 3 1 ")
newarr32 = np.array_split(arr32,3,axis = 1)
print(newarr32)

print("_________________ 4 1")
newarr32 = np.array_split(arr32,4,axis = 1)
print(newarr32)


print("_________________ 5 1")
newarr32 = np.array_split(arr32,5,axis = 1)
print(newarr32)

print("_________________ 6 1")
newarr32 = np.array_split(arr32,6,axis = 1)
print(newarr32)

print("_________________ 1 0")
newarr32 = np.array_split(arr32,1,axis = 0)
print(newarr32)


print("_________________ 2 0")
newarr32 = np.array_split(arr32,2,axis = 0)
print(newarr32)


print("_________________ 3 0")
newarr32 = np.array_split(arr32,3,axis = 0)
print(newarr32)


print("_________________ 4 0")
newarr32 = np.array_split(arr32,4,axis = 0)
print(newarr32)



_________________ 1 1
[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])]
_________________ 2 1
[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]]), array([], shape=(4, 0), dtype=int32)]
_________________ 3 1 
[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]
_________________ 4 1
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]
_________________ 5 1
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]
_________________ 6 1
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int

# Where Function


In [108]:
arr33 = np.array([1,2,3,4,5,6,4,3,2])

x1 = np.where(arr33 == 4)
print(x)

print("_________________")
x = np.where(arr33 % 2 == 0)
print(x)

print("_________________")

xarr = np.array([[1,2],[3,4],[4,5],[7,8]])
xarrans = np.where(xarr == 4)
print(xarrans)

(array([1, 3, 5, 6, 8], dtype=int64),)
_________________
(array([1, 3, 5, 6, 8], dtype=int64),)
_________________
(array([1, 2], dtype=int64), array([1, 0], dtype=int64))


In [132]:
arr32 = ([[1,2,3],[3,4,5],[5,6,4]])
newarr=np.array_split(arr32,3,axis=1)
print(newarr)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([[3],
       [5],
       [4]])]
