In [11]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,4])
print(np.sort(arr1))
arr2=np.array([True,False,True])
print(np.sort(arr2))
arr3=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr3,axis=0))
arr4=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr4,axis=1))

[[1 2 2]
 [3 4 3]
 [4 7 5]]
